<?php
class Home extends AmazonCategory{



    function getName(){
        return 'Home';
    }

    public $_variations_theme = 
		array(
			'Size' => 'Taglia',
            'Color' => 'Colore',
            'Scent' => 'Scent',
			'SizeColor' => 'Taglia e Colore',
            'Size-Scent' => 'Size-Scent',
            'DisplayLength-DisplayWidth' => 'DisplayLength-DisplayWidth',
            'DisplayLength-Material' => 'DisplayLength-Material',
            'DisplayLength-Size' => 'DisplayLength-Size',
            'DisplayLength-Color' => 'DisplayLength-Color',
            'DisplayLength-DisplayHeight' => 'DisplayLength-DisplayHeight',
            'DisplayWidth-Material' => 'DisplayWidth-Material',
            'DisplayWidth-Size' => 'DisplayWidth-Size',
            'DisplayWeight-Color' => 'DisplayWeight-Color',
            'DisplayWeight-DisplayHeight' => 'DisplayWeight-DisplayHeight',
            'Material-DisplayLength' => 'Material-DisplayLength',
            'Material-DisplayWidth' => 'Material-DisplayWidth',
            'Material-Size' => 'Material-Size',
            'Material-Color' => 'Material-Color',
            'Material-DisplayHeight' => 'Material-DisplayHeight',
            'Size-DisplayLength' => 'Size-DisplayLength',
            'Size-DisplayWidth' => 'Size-DisplayWidth',
            'Size-DisplayWeight' => 'Size-DisplayWeight',
            'Size-Material' => 'Size-Material',
            'Size-Color' => 'Size-Color',
            'Size-DisplayHeight' => 'Size-DisplayHeight',
            'Color-DisplayLength' => 'Color-DisplayLength',
            'Color-DisplayWidth' => 'Color-DisplayWidth',
            'Color-ItemPackageQuantity' => 'Color-ItemPackageQuantity',
            'Color-DisplayWeight' => 'Color-DisplayWeight',
            'DisplayHeight' => 'DisplayHeight',
            'Material' => 'Material',
            'DisplayWeight' => 'DisplayWeight',
            'DisplayLength' => 'DisplayLength',
            'ItemPackageQuantity' => 'ItemPackageQuantity',
            'DisplayLength-PatternName' => 'DisplayLength-PatternName',
            'DisplayLength-StyleName' => 'DisplayLength-StyleName',
            'DisplayWidth-PatternName' => 'DisplayWidth-PatternName',
            'DisplayWidth-StyleName' => 'DisplayWidth-StyleName',
            'Occasion-PatternName' => 'Occasion-PatternName',
            'Occasion-ItemPackageQuantity' => 'Occasion-ItemPackageQuantity',
            'Occasion-Material' => 'Occasion-Material',
            'Occasion-StyleName' => 'Occasion-StyleName',
            'Occasion-Size' => 'Occasion-Size',
            'Occasion-Color' => 'Occasion-Color',
            'Occasion-DisplayHeight' => 'Occasion-DisplayHeight',
            'PatternName-DisplayLength' => 'PatternName-DisplayLength',
            'PatternName-DisplayWidth' => 'PatternName-DisplayWidth',
            'PatternName-Occasion' => 'PatternName-Occasion',
            'PatternName-Material' => 'PatternName-Material',
            'PatternName-StyleName' => 'PatternName-StyleName',
            'PatternName-Size' => 'PatternName-Size',
            'PatternName-Color' => 'PatternName-Color',
            'PatternName-DisplayHeight' => 'PatternName-DisplayHeight',
            'MatteStyle-Material' => 'MatteStyle-Material',
            'MatteStyle-StyleName' => 'MatteStyle-StyleName',
            'MatteStyle-Size' => 'MatteStyle-Size',
            'MatteStyle-Color' => 'MatteStyle-Color',
            'ItemPackageQuantity-Occasion' => 'ItemPackageQuantity-Occasion',
            'ItemPackageQuantity-StyleName' => 'ItemPackageQuantity-StyleName',
            'DisplayWeight-StyleName' => 'DisplayWeight-StyleName',
            'Material-PatternName' => 'Material-PatternName',
            'Material-MatteStyle' => 'Material-MatteStyle',
            'Material-StyleName' => 'Material-StyleName',
            'StyleName-DisplayLength' => 'StyleName-DisplayLength',
            'StyleName-DisplayWidth' => 'StyleName-DisplayWidth',
            'StyleName-Occasion' => 'StyleName-Occasion',
            'StyleName-PatternName' => 'StyleName-PatternName',
            'StyleName-DisplayWeight' => 'StyleName-DisplayWeight',
            'StyleName-Material' => 'StyleName-Material',
            'StyleName-Size' => 'StyleName-Size',
            'StyleName-Color' => 'StyleName-Color',
            'Size-Occasion' => 'Size-Occasion',
            'Size-PatternName' => 'Size-PatternName',
            'Size-MatteStyle' => 'Size-MatteStyle',
            'Size-StyleName' => 'Size-StyleName',
            'Color-Occasion' => 'Color-Occasion',
            'Color-PatternName' => 'Color-PatternName',
            'Color-MatteStyle' => 'Color-MatteStyle',
            'Color-StyleName' => 'Color-StyleName',
            'MatteStyle' => 'MatteStyle',
            'PatternName' => 'PatternName',
            'Occasion' => 'Occasion',
            'StyleName' => 'StyleName',
            'CustomerPackageType' => 'CustomerPackageType',
            'ColorName-CustomerPackageType' => 'ColorName-CustomerPackageType',
            'SizeName-CustomerPackageType' => 'SizeName-CustomerPackageType',
            'SizeName-ColorName-CustomerPackageType' => 'SizeName-ColorName-CustomerPackageType',
            'StyleName-CustomerPackageType' => 'StyleName-CustomerPackageType',
            'SizeName-StyleName-CustomerPackageType' => 'SizeName-StyleName-CustomerPackageType',
            'Size' => 'Size',
            'Color' => 'Color',
            'Scent' => 'Scent',
            'CustomerPackageType' => 'CustomerPackageType',
		);

    public $_other_fields = array(
        'StyleName' => array(
            'label' => 'StyleName',
            'type_html' => 'input',
            'required' => false,
            'mapping' => true,
            'themes' => array(
                'DisplayLength-StyleName',
                'SizeName-StyleName-CustomerPackageType',
                'StyleName-CustomerPackageType',
                'StyleName',
                'Color-StyleName',
                'Size-StyleName',
                'StyleName-DisplayLength',
                'StyleName-DisplayWidth',
                'StyleName-Occasion',
                'StyleName-PatternName',
                'StyleName-DisplayWeight',
                'StyleName-Material',
                'StyleName-Size',
                'StyleName-Color',
                'Material-StyleName',
                'DisplayLength-StyleName',
                'DisplayWidth-StyleName',
                'Occasion-StyleName',
                'PatternName-StyleName',
                'MatteStyle-StyleName',
			)
        ),
		'BatteryDescription' => array(
				'label' => 'BatteryDescription',
				'type_html' => 'input',
                'required' => false,
                'mapping' => true,
        ),
        'CanShipInOriginalContainer' => array(
            'label' => 'ColorMap',
            'type_html' => 'input',
            'required' => false,
            'mapping' => true
        ),
        'CountryOfOrigin' => array(
            'label' => 'CountryOfOrigin',
            'type_html' => 'input',
            'required' => false,
            'mapping' => true
        ),
        'CountryProducedIn' => array(
            'label' => 'CountryProducedIn',
            'type_html' => 'input',
            'required' => false,
            'mapping' => true
        ),
    );

}