
# auto-generated by configure
PREFIX = /home2/outletbrand/public_html/lib/classes_4.8.8/lib_img/pngquant-2.12.5
VERSION = 2.12.5
CC = gcc
CFLAGS = -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I./lib -I/usr/include/libpng15     -fexcess-precision=fast
LDFLAGS =  ./lib/libimagequant.a -lpng15   -lz   -lm
SOLIBSUFFIX = so
STATICLIBDEPS = ./lib/libimagequant.h ./lib/libimagequant.a
LIQSRCDIR = ./lib
LIQCONFIGUREFLAGS = '--quiet' 

