DROP TABLE IF EXISTS amazon_report_sync;
DROP TABLE IF EXISTS amazon_feed_sync;
DROP TABLE IF EXISTS amazon_profile;
DROP TABLE IF EXISTS amazon_store;
DROP TABLE IF EXISTS amazon_upload;
DROP TABLE IF EXISTS amazon_asin;
DROP TABLE IF EXISTS amazon_order;
DROP TABLE IF EXISTS amazon_carrier;
DROP TABLE IF EXISTS amazon_feed;
DROP TABLE IF EXISTS amazon_product;
DROP TABLE IF EXISTS amazon_report;
DROP TABLE IF EXISTS amazon_carrier_exit;
DROP TABLE IF EXISTS amazon_order_item;
DROP TABLE IF EXISTS amazon_order_log;
DROP TABLE IF EXISTS amazon_order_log_error;
DROP TABLE IF EXISTS amazon_order;
DROP TABLE IF EXISTS amazon_order_item;
DROP TABLE IF EXISTS amazon_marketplace_setting;

